### PR TITLE
Adds two different kinds of table visualization + docs for non devs

### PR DESCRIPTION
**Pull request by marimeireles**

### CODE REVIEW

**Comment by marimeireles** [comment]
I'm having an issue with travis and I have no idea why:

```
CMake Error at CMakeLists.txt:65 (find_package):

  By not providing "Findtabulate.cmake" in CMAKE_MODULE_PATH this project has

  asked CMake to find a package configuration file provided by "tabulate",

  but CMake did not find one.

  Could not find a package configuration file provided by "tabulate" with any

  of the following names:

    tabulateConfig.cmake

    tabulate-config.cmake

  Add the installation prefix of "tabulate" to CMAKE_PREFIX_PATH or set

  "tabulate_DIR" to a directory containing one of the above files.  If

  "tabulate" provides a separate development package or SDK, be sure it has

  been installed.
```

It works on my Linux. Will try on the Mac tomorrow.
Even though, in my Linux I get some Warnings on Cmake step:

```
CMake Warning at CMakeLists.txt:108 (add_executable):
  Cannot generate a safe runtime search path for target xsqlite because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcrypto.so.1.1] in /usr/lib may be hidden by files in:
      /home/mariana/.conda/envs/xeus-sqlite/lib
    runtime library [libuuid.so.1] in /usr/lib may be hidden by files in:
      /home/mariana/.conda/envs/xeus-sqlite/lib
    runtime library [libsqlite3.so.0] in /usr/lib may be hidden by files in:
      /home/mariana/.conda/envs/xeus-sqlite/lib

  Some of these libraries may not be found correctly.


CMake Warning at CMakeLists.txt:104 (add_library):
  Cannot generate a safe runtime search path for target xeus-sqlite because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libsqlite3.so.0] in /usr/lib may be hidden by files in:
      /home/mariana/.conda/envs/xeus-sqlite/lib
    runtime library [libcrypto.so.1.1] in /usr/lib may be hidden by files in:
      /home/mariana/.conda/envs/xeus-sqlite/lib
    runtime library [libuuid.so.1] in /usr/lib may be hidden by files in:
      /home/mariana/.conda/envs/xeus-sqlite/lib

  Some of these libraries may not be found correctly.

```

**Comment by martinRenou** [comment]
I wonder if it does not find cpp-tabulate because it's installed under `lib64`. Maybe you should add the cmake option `-D CMAKE_INSTALL_LIBDIR=lib` in the `cpp-tabulate-feedstock`

**Comment by marimeireles** [comment]
Oh, thanks for the input. I'll try that. :)

**Comment by martinRenou** [comment]
Still the same issue, but when cpp-tabulate gets installed it's the build `0` that comes, not the build `1`. Hopefully this will be fixed if you try to re-trigger the CI later today.

**Pull request merged**
