### PR TITLE
Enable Windows CI

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Now it seems to compile fine, but we are missing some global data symbols in `SQLiteCpp.lib`, such as

```
extern const int OPEN_READONLY;     // SQLITE_OPEN_READONLY
```

**Comment by SylvainCorlay** [comment]
> `extern const int OPEN_READONLY;     // SQLITE_OPEN_READONLY`

@JohanMabille you may have an idea about this.

**Comment by JohanMabille** [comment]
It looks like these symbols are missing form sqlitecpp.lib. The following command:

```bash
dumpbin /LInKERMEMBER:1 SQLiteCpp.lib /out:res.txt
```

dumps all the symbols from the library, everything but these constants can be found inside. The missing symbols are declared as [extern](https://github.com/SRombauts/SQLiteCpp/blob/cc2e488d1ab5158cc64c102bb6f1edf7fc653a5b/include/SQLiteCpp/Database.h#L35) and defined in the corresponding [source file](https://github.com/SRombauts/SQLiteCpp/blob/cc2e488d1ab5158cc64c102bb6f1edf7fc653a5b/src/Database.cpp#L30), which is correctly included in the CMakeLists.txt of SQLitecpp.

My guess (for having encountering this many times in the past) is that the linker of VS2017 removes external symbols that are not referenced anywhere in the library (which is the case for these symbols). It could be worth trying to build and install sqlitecpp locally to see if you can reproduce the error. If not, the error is in the recipe, otherwise we should open an issue upstream.

**Comment by JohanMabille** [comment]
If you reproduce the error when building sqlitecpp locally, a good workaround to try is to add some methods returning the value of the missing symbols in the source of sqlitecpp. This should prevent the linker from removing the symbols.

**Comment by SylvainCorlay** [comment]
> If you reproduce the error when building sqlitecpp locally, a good workaround to try is to add some methods returning the value of the missing symbols in the source of sqlitecpp. This should prevent the linker from removing the symbols.

I am working remotely this week and only have access to OS X and Linux machines here.

**Pull request closed without merging**
