### PR TITLE
Initial commit try to create a xeus-sqlite binary

### PR DESCRIPTION
**Pull request by marimeireles**

### CODE REVIEW

**Comment by marimeireles** [comment]
Adding the following lines to the cmake:
```
SET(CMAKE_AR "gcc-ar")
SET(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_CXX_ARCHIVE_FINISH true)
```
According to [this](https://stackoverflow.com/questions/39236917/using-gccs-link-time-optimization-with-static-linked-libraries) I can make the static build of xeus-sqlite work, with the following: `cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DXSQL_USE_SHARED_XEUS_SQLITE=OFF ..`

If I try to build xeus statically too with: `cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DXSQL_USE_SHARED_XEUS_SQLITE=OFF -DXSQL_USE_SHARED_XEUS=OFF ..` I get the following:

```
lto1: fatal error: bytecode stream in file '/home/mariana/miniconda3/envs/xvega/lib/libxeus.a' generated with LTO version 6.0 instead of the expected 6.2
compilation terminated.
lto-wrapper: fatal error: /home/mariana/miniconda3/envs/xvega/bin/x86_64-conda-linux-gnu-c++ returned 1 exit status
compilation terminated.
/home/mariana/miniconda3/envs/xvega/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

Complete [err](https://pastebin.com/1y2JE2B4)
ping @JohanMabille 
Thanks!

**Comment by avinal** [comment]
@marimeireles sorry to interrupt in between but I would like to point out something, to build static binaries we must use all static libraries only, hope you are considering this fact. I tried building this few days ago and then I found this.

**Comment by marimeireles** [comment]
Hey @avinal, no problem, thanks for posting. 
That's actually a good point. @SylvainCorlay is the objective for now to do a completely static binary? Or should we pursue this in the future?
Thanks!

**Comment by avinal** [comment]
Thanks @marimeireles , I would like to share my own experiment with you all then, I tried building a static binary but xvega is not linking, when I checked my available libraries and i could not find a static library for xvega (.a) file. I am not sure if they provide a static binary . You may check it that way too.

**Comment by marimeireles** [comment]
Hey @avinal, I talked to Sylvain today and you're right. The point is to make a completely static build.
As you said it will depend on me making xvega static too, so, yeah. I'm gonna tackle that in a near future!
Other than that I think everything else is already available statically.
Thanks for the input! :)

**Pull request merged**
